### ISSUE TITLE
[ENHANCEMENT] Track, display and redirect 404

### ISSUE THREAD

**Issue by Roshyo** [Setono/SyliusRedirectPlugin#37] opened 2019-11-25 11:55 UTC
It would be nice to be able to have an overview of 404 of the shop, so we can propose a redirect creation to the user if too many customers are hitting this page.

**Comment by loevgaard** [comment] 2019-11-25 12:10
Duplicate of #23 ;)

**Comment by Roshyo** [comment] 2019-11-25 12:21
Wow indeed. Didn't remember this issue. Sorry

**Closed** 2019-11-25 12:24 UTC
